config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  devise_for :users

  resources :courses do
  	resources :syllabuses
  end

  resources :syllabuses do
  	resources :chapters
  end

  
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :syllabus

  validates :number, presence: true, numericality: { only_integer: true }, uniqueness: {scope: :syllabus}
  validates :title, presence: true
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :enrollments, dependent: :destroy
    has_many :students, through: :enrollments, class_name: "User"
    has_many :syllabuses,  dependent: :destroy

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
	belongs_to :student, class_name: "User"
    belongs_to :course

    validates :student , uniqueness: true
end

app/models/professor.rb
class Professor < User
	
end

app/models/student.rb
class Student < User
	has_many :enrollments
    has_many :course , through: :enrollments
end

app/models/syllabus.rb
class Syllabus < ActiveRecord::Base
	belongs_to :course
	has_many :chapters, dependent: :destroy

	validates :code , presence: true,  uniqueness: true
	validates :name , presence: true
	validates :semester , presence: true, numericality: { only_integer: true }	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  

  protected  

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :type
  end

  def after_sign_in_path_for(resource)
    # return the path based on resource
    courses_path
  end

end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController

	def index
		@syllabus = Syllabus.find(params[:syllabus_id])
		@chapters = @syllabus.chapters
	end

	def show
		@chapter = Chapter.find(params[:id])
		@syllabus = Syllabus.find(params[:syllabus_id])
	end

	def new
		@chapter = Chapter.new
	end

	def edit
	end

	def create
		@syllabus = Syllabus.find(params[:syllabus_id])
		@chapter  = Chapter.new(chapter_params)
		@chapter.syllabus = Syllabus.find(params[:syllabus_id])
		if @chapter.save
			flash[:notice]  = "Successfully create #{@chapter.title}"
			redirect_to syllabus_chapter_path(@syllabus,@chapter)
		else
			
			render :new
		end
	end

	def update
	end

	def destroy
	end

	private

	def chapter_params
		params.require(:chapter).permit(:number, :title)
	end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	def index
		@courses = Course.all
	end

	def show
		@course = Course.find(params[:id])
	end

	def edit
		@course = Course.find(params[:id])
	end

	def destroy
		
	end
end

app/controllers/syllabuses_controller.rb
class SyllabusesController < ApplicationController	

	def index
		user = current_user
		@course = Course.find(params[:course_id])

		if user.class == Student && user.enrollments.empty?
			enrolment = Enrollment.new
			enrolment.student = current_user
			enrolment.course = @course

			if enrolment.save
				flash[:notice] = "You have been successfully enrolled"
				redirect_to :back
			end
		end
		@course = Course.find(params[:course_id])
		@syllabuses = @course.syllabuses
	end

	def show
		@course = Course.find(params[:course_id])
		@syllabus = Syllabus.find(params[:id])
	end

	def new
		@syllabus = Syllabus.new
	end
	def edit
		@syllabus = Syllabus.find(params[:id])
	end

	def update
		@syllabus = Syllabus.find(params[:id])
		if @syllabus.update(syllabus_params)
			redirect_to course_syllabus_path(@syllabus.course,@syllabus)
		else
			render 'edit'
		end
	end

	def create
		@syllabus  = Syllabus.new(syllabus_params)
		@syllabus.course = Course.find(params[:course_id])
		if @syllabus.save
			flash[:notice]  = "Successfully create #{@syllabus.name}"
			redirect_to course_syllabus_path(@syllabus.course,@syllabus)
		else
			
			render :new
		end
	end

	def destroy
		syllabus = Syllabus.find(params[:id])
		if syllabus.destroy
			flash[:notice] = "Successfully deleted #{syllabus.name}"
			redirect_to :back
		end
	end

	private

	def syllabus_params
		params.require(:syllabus).permit(:code, :semester,:name)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/index.html.erb
<div class="container">
	<h1>Chapters List</h1>
	<table class="table table-hover">
	    <thead>
	        <tr>
	            <th>Number</th>
	            <th>Title</th>	           
	                 
	        </tr>
	    </thead>
	    <tbody>
	    	<% @chapters.each do |chapter| %>
		    	<tr>
		            <td><%= chapter.number %></td>
		            <td><%= chapter.title %></td>
		        </tr>
		    <% end %>
		</tbody>
	</table>
	<% if @chapters.empty? %>
		<p>No Chapters are available to view.</p>
	<% end %>
	
	
	<td><%= link_to "Back", course_syllabuses_path(@syllabus.course), class: "btn btn-default"  %></td> 

	<% if current_user.type == "Professor" %>
		<%= link_to "Create New Chapter", new_syllabus_chapter_path(@syllabus), class: "btn btn-primary"  %>
	<% end %>
</div>

app/views/chapters/new.html.erb
<div class="container">
  <% if @chapter.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@chapter.errors.count, "error") %> prohibited
        this chapter from being saved:
      </h2>
      <ul>
        <% @chapter.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form">  
    <%= form_for(@chapter, url: {action: "create"},  :html => { :role => 'form'}) do |f| %>
      <h3>Create Chapter</h3>
      <div class="form-group">
        <%= f.label :number %>
        <%= f.text_field :number, :autofocus => true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
         
      <%= f.submit 'Create', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/chapters/show.html.erb
<div class="container">

	<h1> Chapter Details </h1>
	<p>
	  <strong>Number:</strong>
	  <%= @chapter.number %>
	</p>

	<p>
	  <strong>Title</strong>
	  <%= @chapter.title %>
	</p>	

	<p>
		<td><%= link_to "Back", syllabus_chapters_path(@syllabus), class: "btn btn-primary"  %></td> 
	</p>

</div>

app/views/courses/index.html.erb
<div class="container">
	<h1>Courses we offer</h1>
	<table class="table table-hover">
	    <thead>
	        <tr>
	            <th>Program</th>
	            <th>Name</th>
	            <th>Duration</th>  
	            <th></th>         
	        </tr>
	    </thead>
	    <tbody>
	    	<% @courses.each do |course| %>
		    	<tr>
		            <td><%= course.code %></td>
		            <td><%= course.name %></td>
		            <td><%= course.duration %> semesters</td>

		            <% if current_user %>

			            <% if current_user.type == "Student"  %>

			            	<% if current_user.enrollments.empty? %>
			            	
			            		<td><%= link_to "Enrol", course_syllabuses_path(course), class: "btn btn-primary"  %></td> 

			            	<% elsif current_user.course.first == course %>

			            		<td><%= link_to "View Syllabus", course_syllabuses_path(course), class: "btn btn-primary"  %></td>

			            	<% else %>

			            		<td></td>

			            	<% end %> 


			            <% else %>

			            	<td><%= link_to "View", course_syllabuses_path(course), class: "btn btn-primary"  %></td>

			            <% end %> 

			        <% else %>

			            <td></td>

			         <% end %>     
		        </tr>
	    	<% end %>	       
	    </tbody>
	</table>
	<% unless current_user %>
		<em>Students, please <a href="<%= new_user_registration_path %>">signup </a>to enroll.</em>
	<% end %>
</div>

app/views/courses/show.html.erb
courses edit

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Chennai Institute of Technology" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main >
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/syllabuses/edit.html.erb
<div class="authform">
  <%= form_for(@syllabus, url: {action: "update"},  :html => { :role => 'form'}) do |f| %>
    <h3>Edit Syllabus</h3>
    <div class="form-group">
      <%= f.label :code %>
      <%= f.text_field :code, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :semester %>
      <%= f.text_field :semester, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>    
    <%= f.submit 'Update', :class => 'button right' %>
  <% end %>
</div>

app/views/syllabuses/index.html.erb
<div class="container">
	<h1><%= "#{@course.code} " "#{@course.name}"%></h1>
	<table class="table table-hover">
	    <thead>
	        <tr>
	            <th>Code</th>
	            <th>Semester</th>
	            <th>Name</th>  
	            <th></th>
	            <th></th>         
	        </tr>
	    </thead>
	    <tbody>
	    	<% @syllabuses.each do |syllabus| %>
		    	<tr>
		            <td><%= syllabus.code %></td>
		            <td><%= syllabus.semester %></td>
		            <td><%= link_to syllabus.name, syllabus_chapters_path(syllabus)  %></td> 
		            <% if current_user.type == "Student" %>
		            	<td></td>   
		            <% else %> 

		            	<td><%= link_to "Edit", edit_course_syllabus_path(@course,syllabus), class: "btn btn-primary"  %></td> 
		            	<td><%= link_to "Delete", course_syllabus_path(@course,syllabus), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"  %></td> 
		            <% end %>    
		        </tr>
	    	<% end %>	       
	    </tbody>
	</table>
		<%= link_to "Back", courses_path, class: "btn btn-default"  %>

	 <% if current_user.type == "Professor" %>
		<%= link_to "Create New Syllabus", new_course_syllabus_path(@course), class: "btn btn-primary"  %>
	<% end %>
</div>

app/views/syllabuses/new.html.erb
<div class="container">
  <% if @syllabus.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@syllabus.errors.count, "error") %> prohibited
        this syllabus from being saved:
      </h2>
      <ul>
        <% @syllabus.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form">  
    <%= form_for(@syllabus, url: {action: "create"},  :html => { :role => 'form'}) do |f| %>
      <h3>Create Syllabus</h3>
      <div class="form-group">
        <%= f.label :code %>
        <%= f.text_field :code, :autofocus => true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :semester %>
        <%= f.text_field :semester, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>    
      <%= f.submit 'Create', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/syllabuses/show.html.erb
<div class="container">

	<h1> Syllabus Details </h1>
	<p>
	  <strong>Code:</strong>
	  <%= @syllabus.code %>
	</p>

	<p>
	  <strong>Semester:</strong>
	  <%= @syllabus.semester %>
	</p>

	<p>
	  <strong>Name:</strong>
	  <%= @syllabus.name %>
	</p>
	 
	<p>
	  <strong>Name:</strong>
	  <%= @syllabus.name %>
	</p>

	<p>
		<td><%= link_to "Back", course_syllabuses_path(@course), class: "btn btn-primary"  %></td> 
	</p>

</div>

app/views/users/_user.html.erb
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>

app/views/welcome/index.html.erb
<div class="jumbotron">
      <div class="container">
        <h1>Chennai Institue of Technology</h1>
        <p>Chennai Institute of Technology shall strive towards becoming a world class institution by producing professionals with a high technical knowledge, professional skills and ethical values. We shall be the preferred partner to the industry and community for our contribution towards their economic and social development by providing high quality manpower through excellence in teaching, research and consultancy. Chennai Institute of Technology shall be recognized as a point of reference, a catalyst, a facilitator, a trend-setter and a leader in technical education.</p>
        <%= link_to "View Courses", courses_path, class: "btn btn-primary btn-lg" %> 
      </div>
</div>
<div class="container">
	<footer>
		<p>&copy; Company 2015</p>
	</footer>
</div>


    